server:
  port: 8000

app:
  jwtSecret: 'my secret'
  jwtExpirationMs: 86400000

spring:
  application:
    name: SpringJwt

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/spring-jwt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
